### ISSUE TITLE
existingResponse="PassThrough" should be added to httpErrors element of Web.config

### ISSUE THREAD

**Issue by Jeavon** [TimGeyssens/UmbracoPageNotFoundManager#1]
Without this the 404 handler won't work on some Web Servers, see https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/50101-404-handler-works-great-locally-not-online for some more info

**Comment by TimGeyssens** [comment]
Yup would be a nice touch

**Comment by TimGeyssens** [comment]
1.6.1 release adds the xdt tranformation for the nuget package so it's just adding the umbraco packages action now

**Comment by TimGeyssens** [comment]
1.6.2 also adds it for the umbraco package
