### ISSUE TITLE
When a domain is set, the wrong 404 page is returned

### ISSUE THREAD

**Issue by marcemarc** [TimGeyssens/UmbracoPageNotFoundManager#3]
Basically what I think happens is that when a domain is not st ContentCache.GetByRoute works from a path /this/is/the/path but if a domain is setup, then ContentCache.GetByRoute expects or needs, I'm not sure which the prefix of the home/root nodes id, eg 1234/this/is/the/path where 1234 is the content id of the homepage node. So I think we just need to use the domain service to look up if any domains are set, match them in the requested url, find the associated content homepage node id, and use that as a prefix in the call to GetByRoute...

**Comment by TimGeyssens** [comment]
Ah must say I haven't tested this with domains, thanks for the pull request!

**Comment by marcemarc** [comment]
doh! - I only tested this with 7.3, sorry
