### ISSUE TITLE
Config file in load-balanced setup

### ISSUE THREAD

**Issue by PhilDye** [TimGeyssens/UmbracoPageNotFoundManager#9]
Probably overlapping with #8, implementing an ICacheRefresher to manage configuration across load-balanced servers (or split backoffice instances) would be useful, eg for hosting in Azure.

**Comment by PhilDye** [comment]
Implemented in #10

**Comment by TimGeyssens** [comment]
1.7.0 is out containing #10, thanks again @PhilDye
